spring:
  # MySql 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4306/mini_commerce
    username:
    password:

  jpa:
    # 서버 시작 시점에 DDL문을 생성하여 DB에 적용한다.
    generate-ddl: true
    # JPA 에 의해 변경된 부분만 적용
    hibernate:
      ddl-auto: update
      # 콘솔창에 출력되는 쿼리를 가독성이 좋게 포맷팅
      format_sql: true
    # 실행되는 쿼리 콘솔 출력
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # 콘솔 출력창 색 변경
  output:
    ansi:
      enabled: always

# 쿼리에 물음표로 출력되는 바인드 파라미터 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

uploadPath: file:///C:/study/dev/spring/mini-commerce/upload/
categoryImgLocation: C:/study/dev/spring/mini-commerce/upload/category
productImgLocation: C:/study/dev/spring/mini-commerce/upload/product

  # swagger
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

